### ISSUE TITLE
ㅤ

### ISSUE THREAD

**Issue by MrinmoyHaloi** [DylanMcBean/PDEA-Encryption#1]

**Comment by MrinmoyHaloi** [comment]
About
No description, website, or topics provided.

**Comment by DylanMcBean** [comment]
As for description. there is a readme file that contains a HowTo that tells you how to use the program, along with this there is an image on how the encryption algorithms functions.

I do not see the need for a website or any topics to be listed/provided so im not sure why that was brought up
